version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: api_postgres_container
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api_typescript
    volumes:
      - ./pgdata:/var/lib/postgresql/data
